### ISSUE TITLE
翻訳もくもく会

### ISSUE THREAD

**Issue by dynamis** [w3c/wot-jp-cg#89]
**タイトル**
WoT 仕様書翻訳タスクフォースミートアップ

併催: [【第47回！】みんなで MDN を翻訳しよう！翻訳コミュニティ定例ミートアップ！](https://mozilla.doorkeeper.jp/events/138783)

**概要**
翻訳のもくもく会を 7/23 13:00-18:00 の MDN ミートアップと併催で実施する

**目的**
WoT 仕様の翻訳のレビューを進める、TD 1.1 の翻訳を始める、など、翻訳作業の進行が止まっているのをリスタートする。参加者の募集をする。

**想定参加者**
Translation TF グループメンバー、その他 W3C/WoT 仕様の日本語化に関心のある方
https://github.com/w3c/wot-jp-cg/tree/main/TF/Translation

**想定実施時期**
7/23 13:00-18:00

**todo**
- [ ] MDN との調整
  - [ ] doorkeeper への追記
- [ ] wot 側の告知
  - [ ] cg ml やサイト
  - [ ] https://wot-jp-cg.netlify.app/docs/event
  - [ ] https://wot-jp-cg.netlify.app/docs/aboutcg#%E7%BF%BB%E8%A8%B3tf
- [ ] lisence についての記載を repo に追記する

**Comment by dynamis** [comment]
MDN側との調整が済み、併催許諾、doorkeeperの記載変更の許可も得られました。

MDNミートアップ案内doorkeeperの書き換えやwotサイトへの変更PRは用意していくので、それを踏まえてWoT側のMLやW3Cサイトでの案内をお願いします。

**Comment by dynamis** [comment]
todo (注意点): W3C ライセンス＆ TTC に掲載される旨を参加者にちゃんと伝えること

**Comment by dynamis** [comment]
その後のやり取りにて、今回は一般参加をして進め方を知りつつ次回に共催をという流れになっており、MDN ミートアップ側の告知ページの記載なども backout 済み。次回日程 (8/27?) での実施を決めてから再度リトライ。
